/**************************************************************************/
/*  Copyright 2004 Gregor Zeitlinger, Bjoern Rabenstein                   */
/*                                                                        */
/*  This file is part of Lummerland.                                      */
/*                                                                        */
/*  Lummerland is free software; you can redistribute it and/or modify    */
/*  it under the terms of the GNU General Public License as published by  */
/*  the Free Software Foundation; either version 2 of the License, or     */
/*  (at your option) any later version.                                   */
/*                                                                        */
/*  Lummerland is distributed in the hope that it will be useful,         */
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of        */
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         */
/*  GNU General Public License for more details.                          */
/*                                                                        */
/*  You should have received a copy of the GNU General Public License     */
/*  along with Lummerland; if not, write to the Free Software             */
/*  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA  */
/** *********************************************************************** */

/* Generated by Together */

package de.berlios.lummerland.gui;

import org.eclipse.swt.SWT;
import org.eclipse.swt.events.DisposeEvent;
import org.eclipse.swt.events.DisposeListener;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.ui.part.ViewPart;

import de.berlios.lummerland.Engine;
import de.berlios.lummerland.gui.board.hex.HexMapAdapter;
import de.berlios.lummerland.gui.layout.LayoutFactory;
import de.berlios.lummerland.gui.player.PlayerWindowArea;
import de.berlios.lummerland.gui.tree.TreeViewableViewer;
import de.berlios.lummerland.gui.tree.XmlNodeViewer;

public class MainView extends ViewPart {

    public static final String ID_VIEW = "de.berlios.lummerland.gui.MainView";
    
    private Engine engine;

    public MainView() {

        this.engine = Engine.getInstance();
        
    }

    /*
     * (non-Javadoc)
     * 
     * @see org.eclipse.ui.part.WorkbenchPart#createPartControl(org.eclipse.swt.widgets.Composite)
     */
    public void createPartControl(Composite parent) {

        parent.setLayout(LayoutFactory.getHorizontalLayout());

        new XmlNodeViewer(parent, engine.getConfig().getDocument());

        new TreeViewableViewer(parent, engine.getRootSchedule());

        Composite composite = new Composite(parent, SWT.BORDER);

        composite.setLayout(LayoutFactory.getVerticalLayout());

        new PlayerWindowArea(composite, engine);

        //        decisionAdapter = pwa.getDecisionAdapter();

        new HexMapAdapter(composite, engine.getBoard());

        parent.addDisposeListener(new DisposeListener() {

            public void widgetDisposed(DisposeEvent arg0) {
                // todo implement widgetDisposed in MainView correctly
                engine.stopRequest();
            }
        });

        parent.addKeyListener(new RootKeyAdapter(engine));
        
        engine.resume();
    }

    /*
     * (non-Javadoc)
     * 
     * @see org.eclipse.ui.part.WorkbenchPart#setFocus()
     */
    public void setFocus() {
        // TODO Auto-generated method stub

    }

}