/**************************************************************************/
/*  Copyright 2004 Gregor Zeitlinger, Bjoern Rabenstein                   */
/*                                                                        */
/*  This file is part of Lummerland.                                      */
/*                                                                        */
/*  Lummerland is free software; you can redistribute it and/or modify    */
/*  it under the terms of the GNU General Public License as published by  */
/*  the Free Software Foundation; either version 2 of the License, or     */
/*  (at your option) any later version.                                   */
/*                                                                        */
/*  Lummerland is distributed in the hope that it will be useful,         */
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of        */
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         */
/*  GNU General Public License for more details.                          */
/*                                                                        */
/*  You should have received a copy of the GNU General Public License     */
/*  along with Lummerland; if not, write to the Free Software             */
/*  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA  */
/** *********************************************************************** */

/* Generated by Together */
package de.berlios.lummerland.board.map;

import java.util.ArrayList;
import java.util.Collection;

import de.berlios.lummerland.Engine;
import de.berlios.lummerland.board.hex.HexEdge;
import de.berlios.lummerland.board.hex.HexTile;
import de.berlios.lummerland.board.tile.Connection;
import de.berlios.lummerland.board.tile.hex.HexStation;
import de.berlios.lummerland.board.tile.hex.HexStationLocation;

public class Board {

    private Engine game;

    public Board(Engine game) {
        this.game = game;

    }

    /**
     * Returns the game.
     * 
     * @return Engine
     */
    public Engine getGame() {
        return game;
    }

    /**
     * @return
     */
    public Collection getTiles() {

        Collection stations = new ArrayList();

        HexStation hexStation = new HexStation(10, 1, HexStationLocation.CENTER);
        stations.add(hexStation);

        Collection connections = new ArrayList();
        connections.add(new Connection(HexEdge.NORTH, hexStation));
        connections.add(new Connection(HexEdge.NORTH, HexEdge.SOUTHWEST));
        connections.add(new Connection(HexEdge.NORTH, HexEdge.SOUTHEAST));

        Collection c = new ArrayList();
        c.add(new HexTile(new MapLocation(0, 0), stations, connections));
        c.add(new HexTile(new MapLocation(0, 2), stations, connections));
        c.add(new HexTile(new MapLocation(0, 4), stations, connections));
        c.add(new HexTile(new MapLocation(1, 1), stations, connections));
        c.add(new HexTile(new MapLocation(1, 3), stations, connections));
        c.add(new HexTile(new MapLocation(2, 0), stations, connections));
        c.add(new HexTile(new MapLocation(2, 2), stations, connections));
        return c;
    }
}